#!/bin/sh

CMD=pdflatex

$CMD main
bibtex main
$CMD main
bibtex main
$CMD main

rm -rf *.aux
rm -rf *.log

# postscript file for submission
# dvips main.dvi
# cp main.ps main-rev1.ps

# ps2pdf13 main.ps
# dvips main

# response to 1st round of reviews
# enscript --margins=30:30:50:40 -f Times-Roman12 --word-wrap -B -p tmp.ps response.txt
# ps2pdf13 tmp.ps

# word count
# pdftk A=main.pdf cat A3-8 output main.pdf.wc
# pdftotext main.pdf.wc - | wc

# pdftk tmp.pdf main.pdf cat output out.pdf
# rm main.pdf tmp.pdf tmp.ps

# the following is needed to keep xpdf from crashing in fullscreen fit width mode
# https://bugs.launchpad.net/ubuntu/+source/xpdf/+bug/352630
export MALLOC_CHECK_=1 

# acroread main.pdf &
#xpdf -z 150 main.pdf &
#xpdf -fullscreen main.pdf &
evince main.pdf &

